apiVersion: v1
kind: Service
metadata:
  name: lego4j
spec:
  selector:
    app: lego4j
  ports:
    - name: http
      protocol: TCP
      port: 7474
      targetPort: 7474
    - name: bolt
      protocol: TCP
      port: 7687
      targetPort: 7687
  type: NodePort
