apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: lego-inventory/front
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
