apiVersion: batch/v1
kind: Job
metadata:
  name: data-provider-init
  labels:
    app: data-provider-init
spec:
  template:
    metadata:
      name: data-provider-init
      labels:
        app: data-provider-init
    spec:
      containers:
        - name: data-provider-init
          image: indyteo/lego-inventory-data-provider
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: lego4j-credentials
                  key: url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: lego4j-credentials
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: lego4j-credentials
                  key: pass
            - name: INITIAL_CATALOG_ITEMS
              value: "S:75283-1,S:75310-1,M:sw1113"
      restartPolicy: Never
