apiVersion: v1
kind: Service
metadata:
  name: data-provider-server
spec:
  selector:
    app: data-provider-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
